name:                yampa-sdl2
version:             0.0.1.0
#synopsis:
#description:
homepage:            https://github.com/Simre1/YampaSDL2#readme
license:             MIT
author:              Simre
maintainer:          simre4775@gmail.com
copyright:           2018 Simre
category:            Graphics,Game
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - Yampa
  - sdl2
  - sdl2-gfx
  - colour
  - StateVar
  - text
  - linear
  - microlens

library:
  source-dirs:      src
  exposed-modules: [YampaSDL2]
tests:
  YampaSDL2-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - base
      - yampa-sdl2
      - Yampa
