name:                yampa-sdl2
version:             0.1.0.0 
synopsis:            Yampa and SDL2 made easy
description:         yampa-sdl2 lets you start coding your app right away instead of dealing with SDL2 first.
homepage:            https://github.com/Simre1/YampaSDL2#readme
license:             MIT
author:              Simre
maintainer:          simre4775@gmail.com
copyright:           2018 Simre
category:            Scene
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - Yampa
  - sdl2
  - colour
  - StateVar
  - text
  - linear
  - vector
  - memoize

library:
  source-dirs:      src
  ghc-options: [-O2]
tests:
  YampaSDL2-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - base
      - yampa-sdl2
      - Yampa
